image: node:12.13-alpine

stages:
  - build
  - quality
  - security
  - tests
  - publish
  - deploy

cache:
  paths:
    - node_modules/
    - yarn.lock
    - .env

Build:
  stage: build
  script:
    - yarn cache clean
    - yarn install
    - yarn build
    - echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env
    - echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
    - export TZ="America/Sao_Paulo"
  only:
    - develop
    - master
    - staging
    - production
  artifacts:
    paths:
      - node_modules/
      - yarn.lock

Lint:
  stage: quality
  script:
    - yarn lint
  only:
    - develop
    - master
    - staging
    - production

Dependencies Violations:
  stage: quality
  script:
    - yarn verify-dependencies-violations
  only:
    - develop
    - master
    - staging
    - production

# Packages Audition:
#   stage: security
#   script:
#     - yarn audit-dependencies
#   only:
#     - develop
#     - master
#     - staging
#     - production

SAST Analyses with Node Scan:
  image: opensecurity/nodejsscan:latest
  stage: security
  script:
    - njsscan src/
  only:
    - develop
    - master
    - staging
    - production

Unit Tests:
  stage: tests
  script:
    - yarn unit-test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    when: always
    paths:
      - test-report.html
    expire_in: 1 days
  only:
    - develop
    - master
    - staging
    - production

Integration Tests:
  stage: tests
  script:
    - yarn integration-test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    when: always
    paths:
      - test-report.html
    expire_in: 1 days
  only:
    - develop
    - master
    - staging
    - production
